---
apiVersion: v1
kind: Secret
metadata:
  name: palauth-session-secret
  namespace: default
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: value

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: palauth
  namespace: default
  labels:
    app: palauth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: palauth
  template:
    metadata:
      labels:
        app: palauth
    spec:
      imagePullSecrets:
        - name: paltiverse-docker
      containers:
        - name: palauth
          image: gitlab.palk.me:5050/paltiverse/palk-redirect:$CI_COMMIT_SHA
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: PAL_HOSTNAME
              value: auth.palk.me
            - name: PAL_OIDC_ID
              value: https://auth.palk.me
            - name: PAL_CAPTCHA_URL
              value: https://captcha.palk.me
            - name: PAL_CAPTCHA_KEY
              valueFrom:
                secretKeyRef:
                  name: friendly-captcha-api-key
                  key: api-key
            - name: PAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: palauth-session-secret
                  key: value
            - name: PAL_PUBLIC_JWK
              valueFrom:
                secretKeyRef:
                  name: palauth-jwk
                  key: public
            - name: PAL_PRIVATE_JWK
              valueFrom:
                secretKeyRef:
                  name: palauth-jwk
                  key: private
            - name: PAL_MAILGUN_KEY
              valueFrom:
                secretKeyRef:
                  name: mailgun-api-key
                  key: api-key
            - name: PAL_MAILGUN_HOST
              value: https://auth.palk.me
            - name: PAL_REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: palauth-redis-url
                  key: redis-url
            - name: NODE_ENV
              value: production
---
apiVersion: v1
kind: Service
metadata:
  name: palauth-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8081
  selector:
    app: palauth
