apiVersion: v1
kind: Secret
metadata:
  name: palauth-session-secret
  namespace: palauth
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: value
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: palauth
  namespace: palauth
  labels:
    app: palauth
spec:
  selector:
    matchLabels:
      app: palauth
  template:
    metadata:
      labels:
        app: palauth
    spec:
      containers:
        - name: palauth
          image: ghcr.io/palkerecsenyi/palauth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 700m
            requests:
              cpu: 300m
          readinessProbe:
            timeoutSeconds: 3
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            timeoutSeconds: 3
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 8080
          env:
            - name: PORT
              value: "8080"
            - name: PAL_HOSTNAME
              value: auth.palk.me
            - name: PAL_OIDC_ID
              value: https://auth.palk.me
            - name: PAL_CAPTCHA_URL
              value: https://captcha.palk.me
            - name: PAL_CAPTCHA_KEY
              valueFrom:
                secretKeyRef:
                  name: friendly-captcha-api-key
                  key: api-key
            - name: PAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: palauth-session-secret
                  key: value
            - name: PAL_PUBLIC_JWK
              valueFrom:
                secretKeyRef:
                  name: palauth-jwk
                  key: public
            - name: PAL_PRIVATE_JWK
              valueFrom:
                secretKeyRef:
                  name: palauth-jwk
                  key: private
            - name: PAL_MAILGUN_KEY
              valueFrom:
                secretKeyRef:
                  name: mailgun-api-key
                  key: api-key
            - name: PAL_MAILGUN_HOST
              value: auth.palk.me
            - name: PAL_REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: palauth-redis-url
                  key: redis-url
            - name: PAL_DB_STRING
              valueFrom:
                secretKeyRef:
                  name: palauth-db-url
                  key: url
            - name: NODE_ENV
              value: production
---
apiVersion: v1
kind: Service
metadata:
  name: palauth-svc
  namespace: palauth
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8081
  selector:
    app: palauth
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: palauth-hpa
  namespace: palauth
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: palauth
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: palauth-ingress
  namespace: palauth
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - auth.palk.me
      secretName: palauth-tls
  rules:
    - host: auth.palk.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: palauth-svc
                port:
                  number: 8081
