name: PalAuth Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: gcr.io/kaniko-project/executor:debug
    defaults:
      run:
        shell: ""
        working-directory: "/"
    steps:
      - uses: actions/checkout@v3
        with:
          entrypoint: ""

      - run: /kaniko/executor --context "${{ github.workspace }}" --dockerfile "${{ github.workspace }}/Dockerfile" --no-push
        with:
          entrypoint: ""
