on:
  push:
    branches:
      - main

jobs:
  build:
    uses: paltiverse/paltiverse-actions/.github/workflows/docker-build.yml@main
    secrets:
      DOCKER_USERNAME: ${{ secrets.PACKAGE_USER }}
      DOCKER_PASSWORD: ${{ secrets.PACKAGE_SECRET }}
  deploy-palcloud:
    uses: paltiverse/paltiverse-actions/.github/workflows/palcloud-deploy.yml@main
    needs: [build]
    secrets:
      PALTIVERSE_K8S: ${{ secrets.PALTIVERSE_K8S }}
      TAILSCALE_TOKEN: ${{ secrets.TAILSCALE_TOKEN }}
    with:
      deployment-file: k8s/deployment.yaml
  deploy-docker-hub:
    uses: paltiverse/paltiverse-actions/.github/workflows/docker-deploy.yml@main
    needs: [build]
    secrets:
      DOCKER_USERNAME: ${{ secrets.PACKAGE_USER }}
      DOCKER_PASSWORD: ${{ secrets.PACKAGE_SECRET }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    with:
      docker-hub-repo: palkerecs/palauth
      docker-hub-version: latest
