name: PalAuth Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/palkerecs/kaniko:alpine
    steps:
      - uses: actions/checkout@v3
      - run: /kaniko/executor --context "${{ github.workspace }}" --dockerfile "${{ github.workspace }}/Dockerfile" --no-push
