name: PalAuth Build
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: alpine:3.19
    steps:
      - run: apk add curl
      - run: curl -k https://kubernetes.default.svc.cluster.local:6443
  build:
    runs-on: ubuntu-latest
    container: docker.io/palkerecs/kaniko:alpine
    steps:
      - uses: actions/checkout@v3
      - run: apk add skopeo
      - run: skopeo login --compat-auth-file /kaniko/.docker/config.json -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} gitea.palk.me
      - run: /kaniko/executor --context "${{ github.workspace }}" --dockerfile "${{ github.workspace }}/Dockerfile" --destination "gitea.palk.me/paltiverse/palauth:${{ github.sha }}"
