on:
  push:
    branches:
      - main

jobs:
  build:
    uses: paltiverse/paltiverse-actions/.github/workflows/docker-build.yml@main
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    uses: paltiverse/paltiverse-actions/.github/workflows/palcloud-deploy.yml@main
    secrets:
      PALTIVERSE_K8S: ${{ secrets.PALTIVERSE_K8S }}
      TAILSCALE_TOKEN: ${{ secrets.TAILSCALE_TOKEN }}
    with:
      deployment-file: k8s/deployment.yaml
