name: PalAuth Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: docker/login-action@v1
        # with:
          # registry: gitea.palk.me
          # username: ${{ github.actor }}
          # password: ${{ secrets.GITHUB_TOKEN }}
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: gitea.palk.me/paltiverse/PalAuth:${{ github.sha }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
