name: PalAuth Build
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: alpine:3.19
    steps:
      - run: apk add tailscale kubectl bash curl
        name: Install dependencies

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          tags: tag:gitea-runners

      - name: Bootstrap kubeconfig
        run: ping paltiverse1
  build:
    runs-on: ubuntu-latest
    container: docker.io/palkerecs/kaniko:alpine
    steps:
      - uses: actions/checkout@v3
      - run: apk add skopeo
      - run: skopeo login --compat-auth-file /kaniko/.docker/config.json -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} gitea.palk.me
      - run: /kaniko/executor --context "${{ github.workspace }}" --dockerfile "${{ github.workspace }}/Dockerfile" --destination "gitea.palk.me/paltiverse/palauth:${{ github.sha }}"
