on:
  push:
    branches:
      - main

jobs:
  deploy-production-migrations:
    runs-on: ubuntu-latest
    container: alpine:3.19
    steps:
      - run: apk add nodejs npm git trurl
      - run: npm install -g corepack node-gyp
      - run: corepack enable
      - uses: actions/checkout@v3
      - run: yarn set version stable
      - run: |
          yarn config set enableGlobalCache false
          yarn config set nodeLinker node-modules
      - run: yarn install
      - uses: https://gitea.palk.me/paltiverse/paltiverse-actions-kubectl@0.0.4
        with:
          tailscale-token: ${{ secrets.TAILSCALE_TOKEN }}
          k8s-config: ${{ secrets.PALTIVERSE_K8S }}
      - run: kubectl -n default port-forward svc/mysql-svc 3306 & PAL_DB_STRING_1=$(kubectl -n palauth get secret palauth-db-url --template='{{ .data.url }}' | base64 -d) PAL_DB_STRING=$(trurl --url $PAL_DB_STRING_1 --set host=localhost --set port=3306) yarn workspace @paltiverse/palauth-backend db:deploy
        name: Run DB migrations
